-- ============================================================
-- O NIVEL QUE FALTAVA NO PLANO DE CONTAS
--
-- RODAR NO PROJETO UNIFICADO (kmkystqgpvmzrccxvyaz).
--
-- ------------------------------------------------------------
-- O QUE ESTAVA FALTANDO
--
-- O plano de contas do Conag tem QUATRO niveis; o nosso tem tres.
--
--   1  ENTRADAS / SAIDAS                    centros_custo.tipo
--   2  OPERACIONAL | INSUMOS AGROPECUARIOS  centros_custo.subcategoria
--   3  INSUMOS AGRICOLAS                    <-- nao existia
--   4  ADUBOS E FERTILIZANTES               centros_custo.nome
--
-- O nivel 3 separa INSUMO AGRICOLA de INSUMO PECUARIO dentro do mesmo
-- grupo, MAO-DE-OBRA de REFEITORIO dentro de mao de obra, MANUTENCAO DE
-- MAQUINAS de MANUTENCAO DE INFRAESTRUTURA. Sem ele, "quanto gastei de
-- insumo na lavoura" so sai somando conta por conta na mao.
--
-- Ele se perdeu na migracao do Conag. Este script devolve.
--
-- ------------------------------------------------------------
-- DE ONDE VEM
--
-- Do balancete do proprio Conag, rodado em 27/08/2026 de 2014 a 2030 com
-- todas as fazendas e atividades - ele imprime a arvore inteira. Sao 95
-- pares (subcategoria, conta) em 40 classes.
--
-- A chave e SUBCATEGORIA + NOME, nao so o nome: existe uma conta chamada
-- TRIBUTOS em duas subcategorias diferentes, cada uma numa classe. Casar
-- so pelo nome poria as duas na mesma.
--
-- Conta que nao aparecer aqui e conta sem movimento no Conag, ou nossa e
-- nao deles. Fica com classe nula e a consulta do fim lista quais sao.
-- ============================================================

do $$
begin
  if not exists (select 1 from information_schema.tables
                 where table_schema='public' and table_name='talhoes_areas') then
    raise exception 'PROJETO ERRADO';
  end if;
end $$;

alter table centros_custo add column if not exists classe text;

comment on column centros_custo.classe is
  'Nivel 3 do plano de contas, entre a subcategoria e o nome da conta. '
  'Ex: subcategoria OPERACIONAL | INSUMOS AGROPECUARIOS, classe INSUMOS '
  'AGRICOLAS, nome ADUBOS E FERTILIZANTES. Veio do balancete do Conag.';


-- A comparacao ignora acento, caixa e espaco repetido: nossos nomes vieram
-- de importacao e nem sempre batem caractere a caractere com a tela deles.
-- unaccent em vez de translate com a tabela de acentos escrita a mao: o
-- arquivo fica sem um unico caractere acentuado, e o separador de
-- statements do editor do Supabase nao tem como se perder nele.
create extension if not exists unaccent;

create or replace function normaliza_conta(t text) returns text
language sql immutable as $$
  select upper(btrim(regexp_replace(
    unaccent(coalesce(t,'')), '[[:space:]]+', ' ', 'g')));
$$;


with mapa(subcategoria, conta, classe) as (values
    ('ADM | DESPESAS COM ADMINISTRACAO', 'AGUA', 'DESPESAS COM INSTALACOES - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'ALUGUEL', 'DESPESAS COM INSTALACOES - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'CARTORIO', 'SERVICOS PROFISSIONAIS'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'COMUNICACAO E TELEFONIA', 'DESPESAS COM INSTALACOES - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'CONTABILIDADE', 'SERVICOS PROFISSIONAIS'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'CORREIOS E TRANSPORTES', 'DESPESAS GERAIS - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'DESPESAS COM A CASA-SEDE', 'DESPESAS COM A CASA-SEDE'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'DESPESAS GERAIS DA ADMINISTRACAO', 'DESPESAS GERAIS - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'DESPESAS GERAIS NA CASA-SEDE', 'DESPESAS COM A CASA-SEDE'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'DOACOES', 'DOACOES'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'ENERGIA ELETRICA', 'DESPESAS COM INSTALACOES - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'HIGIENE E LIMPEZA', 'DESPESAS COM INSTALACOES - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'JURIDICO', 'SERVICOS PROFISSIONAIS'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'LICENCAS E TAXAS', 'DESPESAS GERAIS - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'MANUTENCAO DOS VEICULOS DA ADMINISTRACAO', 'DESPESAS COM VEICULOS - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'MANUTENCAO E PRESTADORES DE SERVICO NA CASA-SEDE', 'DESPESAS COM A CASA-SEDE'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'MANUTENCAO GERAL DO ESCRITORIO', 'DESPESAS COM INSTALACOES - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'MULTAS E OUTRAS INDENIZACOES', 'DESPESAS COM VEICULOS - ADMINISTRACAO'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'OUTROS BENEFICIOS', 'DESPESAS COM SOCIOS E DIRIGENTES'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'OUTROS SERVICOS PROFISSIONAIS', 'SERVICOS PROFISSIONAIS'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'SEGURANCA E VIGILANCIA', 'SERVICOS PROFISSIONAIS'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'TECNOLOGIA E SOFTWARE', 'SERVICOS PROFISSIONAIS'),
    ('ADM | DESPESAS COM ADMINISTRACAO', 'VIAGENS E ESTADIAS', 'DESPESAS GERAIS - ADMINISTRACAO'),
    ('ATIVIDADES DE FINANCIAMENTO', 'APORTE DE CAPITAL DE TERCEIROS (FUNDOS DE INVESTIMENTOS, NOVOS SOCIOS, OUTROS)', 'INTEGRALIZACAO DE CAPITAL'),
    ('ATIVIDADES DE FINANCIAMENTO', 'RENDIMENTOS DE APLICACOES FINANCEIRAS', 'RECEITAS FINANCEIRAS'),
    ('ATIVIDADES DE INVESTIMENTO', 'VENDA DE VEICULOS, MAQUINAS E EQUIPAMENTOS', 'ALIENACAO DE ATIVOS'),
    ('ATIVIDADES OPERACIONAIS', 'PRESTACAO DE SERVICOS AGROPECUARIOS', 'RECEITA COM PRESTACAO DE SERVICOS'),
    ('ATIVIDADES OPERACIONAIS', 'RECEBIMENTO DE ARRENDAMENTO DE TERRAS', 'RECEITA COM ARRENDAMENTO DE TERRAS E PARCERIAS'),
    ('ATIVIDADES OPERACIONAIS', 'RECEITA COM PRODUCAO AGROPECUARIA - VENDA FISICA', 'PRODUCAO AGROPECUARIA'),
    ('COMERCIAL | DESPESAS COM COMERCIALIZACAO', 'FRETE PARA COMERCIALIZACAO DA PRODUCAO AGROPECUARIA', 'ARMAZENAGEM & LOGISTICA'),
    ('DESPESAS | PARTICIPACOES NOS RESULTADOS', 'BONUS DOS FUNCIONARIOS DA(S) FAZENDA(S)', 'PARTICIPACAO NOS LUCROS E RESULTADOS (PLR)'),
    ('FINANCIAMENTOS | AMORTIZACAO DE FINANCIAMENTOS', 'AMORTIZACAO DE FINANCIAMENTO', 'AMORTIZACOES DE EMPRESTIMOS E FINANCIAMENTOS'),
    ('FINANCIAMENTOS | DESPESAS FINANCEIRAS', 'DESPESAS COM CARTORIO PARA CONTRATOS DE FINANCIAMENTO', 'CUSTAS CONTRATUAIS'),
    ('FINANCIAMENTOS | DESPESAS FINANCEIRAS', 'IOF', 'CUSTAS CONTRATUAIS'),
    ('FINANCIAMENTOS | DESPESAS FINANCEIRAS', 'JUROS PAGOS OU INCORRIDOS', 'DESPESAS FINANCEIRAS'),
    ('FINANCIAMENTOS | DESPESAS FINANCEIRAS', 'PROJETOS TECNICOS', 'CUSTAS CONTRATUAIS'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'AQUISICAO DE MAQUINAS, CAMINHOES E EQUIPAMENTOS', 'INVESTIMENTO EM ATIVOS'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'COMPRA DE ANIMAIS PARA RECRIA, ENGORDA E ABATE', 'INVESTIMENTO EM ANIMAIS'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'COMPRA DE EQUINOS', 'INVESTIMENTO EM ANIMAIS'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'COMPRA DE MATRIZES PARA REPRODUCAO', 'INVESTIMENTO EM ANIMAIS'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'INVESTIMENTO EM CONSORCIO (NAO CONTEMPLADO)', 'INVESTIMENTO FINANCEIRO'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'INVESTIMENTO EM TERRAS', 'INVESTIMENTO EM ATIVOS'),
    ('INVESTIMENTOS | SAIDA PARA INVESTIMENTOS', 'INVESTIMENTOS EM INFRAESTRUTURA', 'INVESTIMENTO EM ATIVOS'),
    ('OPERACIONAL | ARRENDAMENTO DE TERRAS E PARCERIAS', 'ARRENDAMENTO DE AREA PRODUTIVA', 'ALUGUEL DE AREA PRODUTIVA'),
    ('OPERACIONAL | ENERGIA ELETRICA DA FAZENDA', 'ENERGIA ELETRICA DA FAZENDA', 'ENERGIA ELETRICA DE INFRAESTRUTURA OPERACIONAL'),
    ('OPERACIONAL | GASTOS COM COMBUSTIVEIS', 'COMBUSTIVEL PARA FROTA TRATORES, MAQUINAS E VEICULOS DA OPERACAO', 'COMBUSTIVEIS DA OPERACAO AGROPECUARIA'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'ADUBOS E FERTILIZANTES', 'INSUMOS AGRICOLAS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'CORRETIVOS DE SOLO', 'INSUMOS AGRICOLAS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'DEFENSIVOS AGRICOLAS', 'INSUMOS AGRICOLAS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'EMBALAGENS, SACARIAS E LONAS', 'INSUMOS AGRICOLAS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'FERRAMENTAS E UTENSILIOS PARA MANEJO', 'INSUMOS PECUARIOS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'NUTRICAO ANIMAL', 'INSUMOS PECUARIOS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'REPRODUCAO ANIMAL', 'INSUMOS PECUARIOS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'SANIDADE ANIMAL', 'INSUMOS PECUARIOS'),
    ('OPERACIONAL | INSUMOS AGROPECUARIOS', 'SEMENTES E MUDAS DE PLANTIO', 'INSUMOS AGRICOLAS'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'MANUTENCAO DA FROTA DE VEICULOS, MAQUINAS E EQUIPAMENTOS DE CAMPO', 'MANUTENCAO DE TRATORES, CAMINHOES, MAQUINAS, EQUIPAMENTOS E IMPLEMENTOS'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'MANUTENCAO DE ESTRADAS E CARREADORES', 'MANUTENCAO E REPARO DE INFRAESTRUTURAS'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'MANUTENCAO DE INFRAESTRUTURA', 'MANUTENCAO E REPARO DE INFRAESTRUTURAS'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'MATERIAIS DE OFICINA', 'DESPESAS COM OFICINA'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'REDE ELETRICA', 'MANUTENCAO E REPARO DE INFRAESTRUTURAS'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'REDE HIDRICA', 'MANUTENCAO E REPARO DE INFRAESTRUTURAS'),
    ('OPERACIONAL | MANUTENCAO GERAL DA FAZENDA', 'SEGURO DE MAQUINAS E EQUIPAMENTOS', 'MANUTENCAO DE TRATORES, CAMINHOES, MAQUINAS, EQUIPAMENTOS E IMPLEMENTOS'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', '13O SALARIO', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'AQUISICAO DE REFEICOES PRONTAS', 'REFEITORIO, RESTAURANTES & ALIMENTACAO'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'COMPRA DE ALIMENTOS', 'REFEITORIO, RESTAURANTES & ALIMENTACAO'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'DIARISTA', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'EXAME MEDICO OCUPACIONAL E PERIODICO', 'GASTOS COM PESSOAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'FERIAS', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'FGTS', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'GRATIFICACOES', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'IMPOSTO DE RENDA - FOLHA DE PAGAMENTO', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'MATERIAIS DE LIMPEZA', 'REFEITORIO, RESTAURANTES & ALIMENTACAO'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'OUTROS ENCARGOS', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'PAGAMENTO DE SERVICOS TERCEIRIZADOS RELACIONADOS AO REFEITORIO', 'REFEITORIO, RESTAURANTES & ALIMENTACAO'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'PLANO DE SAUDE', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'RESCISAO', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'SALARIOS', 'MAO-DE-OBRA DE OPERACIONAL'),
    ('OPERACIONAL | MAO DE OBRA OPERACIONAL', 'SEGURANCA DO TRABALHO E EPI', 'GASTOS COM PESSOAL'),
    ('OPERACIONAL | OUTROS CUSTOS', 'OUTROS SEGUROS', 'CONTRATACAO DE SEGUROS'),
    ('OPERACIONAL | OUTROS CUSTOS', 'SEGUROS AGROPECUARIOS (SEGURO DE SAFRA)', 'CONTRATACAO DE SEGUROS'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'ALUGUEL DE MAQUINAS E EQUIPAMENTOS', 'TERCEIRIZACAO DE SERVICOS AGROPECUARIOS'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'ANALISES AGRICOLAS (SOLO, FOLHA, ETC)', 'TERCEIRIZACAO DE SERVICOS AGROPECUARIOS'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'FRETE COMPRA DE PRODUTOS', 'TERCEIRIZACAO DE SERVICOS AGROPECUARIOS'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'FRETE DE ANIMAIS', 'TERCEIRIZACAO DE SERVICOS AGROPECUARIOS'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'PRESTACAO DE SERVICOS PARA O CAMPO', 'TERCEIRIZACAO DE SERVICOS AGROPECUARIOS'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'SERVICOS TECNICOS PROFISSIONAIS', 'SERVICOS TECNICOS PROFISSIONAIS (CONSULTORIAS DE CAMPO)'),
    ('OPERACIONAL | PRESTACAO DE SERVICOS', 'TERCEIRIZACAO DE COLHEITA', 'TERCEIRIZACAO DE SERVICOS AGROPECUARIOS'),
    ('TRIBUTOS | IMPOSTOS SOBRE LUCRO', 'TRIBUTOS', 'DEDUCOES DA RECEITA BRUTA DE VENDAS'),
    ('TRIBUTOS | TRIBUTOS E CONTRIBUICOES', 'IMPOSTO DE RENDA SOBRE LUCRO LIQUIDO', 'TRIBUTOS E CONTRIBUICOES'),
    ('TRIBUTOS | TRIBUTOS E CONTRIBUICOES', 'TRIBUTOS', 'TRIBUTOS E CONTRIBUICOES'),
    ('VARIACOES NAO OPERACIONAIS DE CAIXA', 'AJUSTE DE SALDO BANCARIO', 'VARIACOES DE CAIXA NAO OPERACIONAL'),
    ('VARIACOES NAO OPERACIONAIS DE CAIXA', 'ESTORNO E/OU DEVOLUCAO DE PAGAMENTO', 'VARIACOES DE CAIXA NAO OPERACIONAL'),
    ('VARIACOES NAO OPERACIONAIS DE CAIXA', 'OUTRAS MOVIMENTACOES DE CAIXA', 'VARIACOES DE CAIXA NAO OPERACIONAL'),
    ('VARIACOES NAO OPERACIONAIS DE CAIXA', 'OUTROS RECEBIMENTOS NAO RELACIONADOS A ATIVIDADE RURAL', 'OUTRAS RECEITAS NAO OPERACIONAIS'),
    ('VARIACOES NAO OPERACIONAIS DE CAIXA', 'RESGATE DE APLICACOES FINANCEIRAS', 'APLICACOES FINANCEIRAS')
)
update centros_custo c
   set classe = m.classe
  from mapa m
 where normaliza_conta(c.nome) = m.conta
   and normaliza_conta(c.subcategoria) = m.subcategoria
   and c.classe is distinct from m.classe;


-- ------------------------------------------------------------
-- CONFERE - uma consulta so
-- ------------------------------------------------------------
select 1 as ordem, 'Centros com classe' as item,
       (count(*) filter (where classe is not null))::text as valor,
       (count(*) filter (where classe is not null) || ' de ' || count(*)) as situacao
from centros_custo
union all
select 2, 'Classes distintas', count(distinct classe)::text, 'no Conag sao 40'
from centros_custo where classe is not null
union all
select 3, 'Total dos lancamentos', round(sum(valor),2)::text,
       'tem que continuar 10447812.29'
from lancamentos_financeiros
union all
select 4, 'SEM CLASSE: ' || c.nome,
       count(l.id)::text,
       'R$ ' || coalesce(round(sum(l.valor),2), 0)::text || ' | ' || coalesce(c.subcategoria,'sem grupo')
from centros_custo c
left join lancamentos_financeiros l on l.centro_custo_id = c.id
where c.classe is null
group by c.nome, c.subcategoria
order by ordem, item;
